# Generated by Django 3.0.5 on 2020-10-23 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=254)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
                ('product_category', models.CharField(choices=[('Indian & Fusion Wear', 'Indian & Fusion Wear'), ('Western Wear', 'Western Wear'), ('Jewellery', 'Jewellery'), ('Accessories', 'Accessories')], max_length=50, null=True)),
                ('sub_category', models.CharField(choices=[('Kurtis, Tunics & Tops', 'Kurtis, Tunics & Tops'), ('Sarees', 'Sarees'), ('Skirts & Palazzos', 'Skirts & Palazzos'), ('Ethnic Dresses', 'Ethnic Dresses'), ('Lehenga Cholis', 'Lehenga Cholis'), ('Dupattas & Shawls', 'Dupattas & Shawls'), ('Dresses', 'Dresses'), ('Jumpsuits', 'Jumpsuits'), ('Tops, T-Shirts & Shirts', 'Tops, T-Shirts & Shirts'), ('Jeans & Jeggings', 'Jeans & Jeggings'), ('Trousers & Capris', 'Trousers & Capris'), ('Shorts & Skirts', 'Shorts & Skirts'), ('Shrugs', 'Shrugs'), ('Sweaters & Sweatshirts', 'Sweaters & Sweatshirts'), ('Jackets & Coats', 'Jackets & Coats'), ('Blazers & Waistcoats', 'Blazers & Waistcoats'), ('Leggings, Salwars & Churidars', 'Leggings, Salwars & Churidars'), ('Ponchoo', 'Ponchoo')], max_length=50, null=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('Plus Size', 'Plus Size')], max_length=20, null=True)),
                ('fabric', models.CharField(choices=[('Cotton', 'Cotton'), ('Silk', 'Silk'), ('Chiffon', 'Chiffon'), ('Woolen', 'Woolen'), ('Viscos', 'Viscos'), ('Rayon', 'Rayon'), ('Georegette', 'Georegette'), ('Synthetic', 'Synthetic')], max_length=20, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('brand', models.CharField(default=None, max_length=256)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Seller', verbose_name='seller_id')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('tracking_id', models.CharField(default=None, max_length=256)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
    ]
