# Generated by Django 3.0.5 on 2020-10-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20201025_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(default=132103),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(default='ywehbjdschew122132', max_length=50),
            preserve_default=False,
        ),
    ]
