# Generated by Django 3.0.5 on 2020-10-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20201025_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='Huda 851', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(default='90311002010', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.CharField(default='132103', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
